// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

using System;
using System.Security.Cryptography;
using System.Text;
using StreamChat;
using StreamChat.Models;
using Xunit;

namespace StreamChat.Tests
{
    public class WebhookTests
    {
        private const string TestSecret = "test-webhook-secret";
        private const string TestBody = "{\"type\":\"test.event\"}";

        private static string ComputeSignature(string body, string secret)
        {
            using var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(secret));
            var hash = hmac.ComputeHash(Encoding.UTF8.GetBytes(body));
            return Convert.ToHexString(hash).ToLowerInvariant();
        }

        [Fact]
        public void VerifySignature_ValidSignature_ReturnsTrue()
        {
            var signature = ComputeSignature(TestBody, TestSecret);
            Assert.True(Webhook.VerifySignature(TestBody, signature, TestSecret));
        }

        [Fact]
        public void VerifySignature_WrongSignature_ReturnsFalse()
        {
            Assert.False(Webhook.VerifySignature(TestBody, "invalidsignature", TestSecret));
        }

        [Fact]
        public void VerifySignature_TamperedBody_ReturnsFalse()
        {
            var signature = ComputeSignature(TestBody, TestSecret);
            Assert.False(Webhook.VerifySignature("{\"type\":\"tampered\"}", signature, TestSecret));
        }

        [Fact]
        public void VerifySignature_WrongSecret_ReturnsFalse()
        {
            var signature = ComputeSignature(TestBody, TestSecret);
            Assert.False(Webhook.VerifySignature(TestBody, signature, "wrong-secret"));
        }

        [Fact]
        public void VerifySignature_EmptySignature_ReturnsFalse()
        {
            Assert.False(Webhook.VerifySignature(TestBody, "", TestSecret));
        }

        [Fact]
        public void GetEventType_ValidPayload_ReturnsType()
        {
            Assert.Equal("message.new", Webhook.GetEventType("{\"type\":\"message.new\"}"));
        }

        [Fact]
        public void GetEventType_MissingTypeField_ReturnsNull()
        {
            Assert.Null(Webhook.GetEventType("{\"foo\":\"bar\"}"));
        }

        [Fact]
        public void GetEventType_InvalidJson_ReturnsNull()
        {
            Assert.Null(Webhook.GetEventType("not json"));
        }

        [Fact]
        public void GetEventType_EmptyObject_ReturnsNull()
        {
            Assert.Null(Webhook.GetEventType("{}"));
        }
        [Fact]
        public void ParseWebhookEvent_AppealAccepted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"appeal.accepted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<AppealAcceptedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_AppealCreated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"appeal.created\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<AppealCreatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_AppealRejected_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"appeal.rejected\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<AppealRejectedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ExportBulkImageModerationError_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"export.bulk_image_moderation.error\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<AsyncExportErrorEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ExportBulkImageModerationSuccess_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"export.bulk_image_moderation.success\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<AsyncBulkImageModerationEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ExportModerationLogsError_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"export.moderation_logs.error\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<AsyncExportErrorEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ExportModerationLogsSuccess_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"export.moderation_logs.success\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<AsyncExportModerationLogsEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityAdded_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.added\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityAddedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityFeedback_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.feedback\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityFeedbackEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityMarked_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.marked\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityMarkEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityPinned_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.pinned\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityPinnedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityReactionAdded_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.reaction.added\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityReactionAddedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityReactionDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.reaction.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityReactionDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityReactionUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.reaction.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityReactionUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityRemovedFromFeed_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.removed_from_feed\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityRemovedFromFeedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityRestored_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.restored\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityRestoredEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityUnpinned_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.unpinned\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityUnpinnedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsActivityUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.activity.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ActivityUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsBookmarkAdded_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.bookmark.added\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<BookmarkAddedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsBookmarkDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.bookmark.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<BookmarkDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsBookmarkUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.bookmark.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<BookmarkUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsBookmarkFolderDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.bookmark_folder.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<BookmarkFolderDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsBookmarkFolderUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.bookmark_folder.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<BookmarkFolderUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsCommentAdded_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.comment.added\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<CommentAddedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsCommentDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.comment.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<CommentDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsCommentReactionAdded_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.comment.reaction.added\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<CommentReactionAddedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsCommentReactionDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.comment.reaction.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<CommentReactionDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsCommentReactionUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.comment.reaction.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<CommentReactionUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsCommentUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.comment.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<CommentUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFeedCreated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.feed.created\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FeedCreatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFeedDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.feed.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FeedDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFeedUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.feed.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FeedUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFeedGroupChanged_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.feed_group.changed\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FeedGroupChangedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFeedGroupDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.feed_group.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FeedGroupDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFeedMemberAdded_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.feed_member.added\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FeedMemberAddedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFeedMemberRemoved_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.feed_member.removed\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FeedMemberRemovedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFeedMemberUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.feed_member.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FeedMemberUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFollowCreated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.follow.created\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FollowCreatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFollowDeleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.follow.deleted\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FollowDeletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsFollowUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.follow.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<FollowUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsNotificationFeedUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.notification_feed.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<NotificationFeedUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_FeedsStoriesFeedUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"feeds.stories_feed.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<StoriesFeedUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ModerationCustomAction_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"moderation.custom_action\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ModerationCustomActionEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ModerationFlagged_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"moderation.flagged\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ModerationFlaggedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ModerationMarkReviewed_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"moderation.mark_reviewed\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ModerationMarkReviewedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ModerationCheckCompleted_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"moderation_check.completed\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ModerationCheckCompletedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ReviewQueueItemNew_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"review_queue_item.new\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ReviewQueueItemNewEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_ReviewQueueItemUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"review_queue_item.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<ReviewQueueItemUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_UserBanned_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"user.banned\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<UserBannedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_UserDeactivated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"user.deactivated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<UserDeactivatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_UserReactivated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"user.reactivated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<UserReactivatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_UserUpdated_ReturnsCorrectType()
        {
            var payload = "{\"type\":\"user.updated\"}";
            var result = Webhook.ParseWebhookEvent(payload);
            Assert.IsType<UserUpdatedEvent>(result);
        }

        [Fact]
        public void ParseWebhookEvent_UnknownType_ThrowsException()
        {
            Assert.Throws<Webhook.WebhookException>(() =>
            {
                Webhook.ParseWebhookEvent("{\"type\":\"unknown.event\"}");
            });
        }

        [Fact]
        public void ParseWebhookEvent_MissingType_ThrowsException()
        {
            Assert.Throws<Webhook.WebhookException>(() =>
            {
                Webhook.ParseWebhookEvent("{\"foo\":\"bar\"}");
            });
        }

        [Fact]
        public void ParseWebhookEvent_InvalidJson_ThrowsException()
        {
            Assert.Throws<Webhook.WebhookException>(() =>
            {
                Webhook.ParseWebhookEvent("not json");
            });
        }
    }
}
