// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace GetStream
{
    public interface IClient
    {
        Task<StreamResponse<TResponse>> MakeRequestAsync<TRequest, TResponse>(
            string method,
            string path,
            Dictionary<string, string>? queryParams,
            TRequest? requestBody,
            Dictionary<string, string>? pathParams,
            CancellationToken cancellationToken = default);
    }
} 