// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.
using System.Text.Json.Serialization;
using GetStream.Models;

namespace GetStream.Requests
{
    public class AcceptFeedMemberInviteRequest
    {
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class AcceptFollowRequest
    {
        [JsonPropertyName("source")]
        public string Source { get; set; }
        [JsonPropertyName("target")]
        public string Target { get; set; }
        [JsonPropertyName("follower_role")]
        public string? FollowerRole { get; set; }
    }
    public class ActivityFeedbackRequest
    {
        [JsonPropertyName("hide")]
        public bool? Hide { get; set; }
        [JsonPropertyName("mute_user")]
        public bool? MuteUser { get; set; }
        [JsonPropertyName("reason")]
        public string? Reason { get; set; }
        [JsonPropertyName("report")]
        public bool? Report { get; set; }
        [JsonPropertyName("show_less")]
        public bool? ShowLess { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class AddActivityRequest
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }
        [JsonPropertyName("feeds")]
        public List<string> Feeds { get; set; }
        [JsonPropertyName("expires_at")]
        public string? ExpiresAt { get; set; }
        [JsonPropertyName("id")]
        public string? ID { get; set; }
        [JsonPropertyName("parent_id")]
        public string? ParentID { get; set; }
        [JsonPropertyName("poll_id")]
        public string? PollID { get; set; }
        [JsonPropertyName("text")]
        public string? Text { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("visibility")]
        public string? Visibility { get; set; }
        [JsonPropertyName("visibility_tag")]
        public string? VisibilityTag { get; set; }
        [JsonPropertyName("attachments")]
        public List<Attachment> Attachments { get; set; }
        [JsonPropertyName("filter_tags")]
        public List<string> FilterTags { get; set; }
        [JsonPropertyName("interest_tags")]
        public List<string> InterestTags { get; set; }
        [JsonPropertyName("mentioned_user_ids")]
        public List<string> MentionedUserIds { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("location")]
        public ActivityLocation? Location { get; set; }
        [JsonPropertyName("search_data")]
        public object SearchData { get; set; }
    }
    public class AddBookmarkRequest
    {
        [JsonPropertyName("folder_id")]
        public string? FolderID { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("new_folder")]
        public AddFolderRequest? NewFolder { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class AddCommentReactionRequest
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }
        [JsonPropertyName("create_notification_activity")]
        public bool? CreateNotificationActivity { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class AddCommentRequest
    {
        [JsonPropertyName("comment")]
        public string Comment { get; set; }
        [JsonPropertyName("object_id")]
        public string ObjectID { get; set; }
        [JsonPropertyName("object_type")]
        public string ObjectType { get; set; }
        [JsonPropertyName("create_notification_activity")]
        public bool? CreateNotificationActivity { get; set; }
        [JsonPropertyName("parent_id")]
        public string? ParentID { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("attachments")]
        public List<Attachment> Attachments { get; set; }
        [JsonPropertyName("mentioned_user_ids")]
        public List<string> MentionedUserIds { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class AddCommentsBatchRequest
    {
        [JsonPropertyName("comments")]
        public List<AddCommentRequest> Comments { get; set; }
    }
    public class AddReactionRequest
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }
        [JsonPropertyName("create_notification_activity")]
        public bool? CreateNotificationActivity { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class BanRequest
    {
        [JsonPropertyName("target_user_id")]
        public string TargetUserID { get; set; }
        [JsonPropertyName("banned_by_id")]
        public string? BannedByID { get; set; }
        [JsonPropertyName("channel_cid")]
        public string? ChannelCid { get; set; }
        [JsonPropertyName("delete_messages")]
        public string? DeleteMessages { get; set; }
        [JsonPropertyName("ip_ban")]
        public bool? IpBan { get; set; }
        [JsonPropertyName("reason")]
        public string? Reason { get; set; }
        [JsonPropertyName("shadow")]
        public bool? Shadow { get; set; }
        [JsonPropertyName("timeout")]
        public int? Timeout { get; set; }
        [JsonPropertyName("banned_by")]
        public UserRequest? BannedBy { get; set; }
    }
    public class BlockUsersRequest
    {
        [JsonPropertyName("blocked_user_id")]
        public string BlockedUserID { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class BulkImageModerationRequest
    {
        [JsonPropertyName("csv_file")]
        public string CsvFile { get; set; }
    }
    public class CastPollVoteRequest
    {
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
        [JsonPropertyName("vote")]
        public VoteData? Vote { get; set; }
    }
    public class CheckPushRequest
    {
        [JsonPropertyName("apn_template")]
        public string? ApnTemplate { get; set; }
        [JsonPropertyName("event_type")]
        public string? EventType { get; set; }
        [JsonPropertyName("firebase_data_template")]
        public string? FirebaseDataTemplate { get; set; }
        [JsonPropertyName("firebase_template")]
        public string? FirebaseTemplate { get; set; }
        [JsonPropertyName("message_id")]
        public string? MessageID { get; set; }
        [JsonPropertyName("push_provider_name")]
        public string? PushProviderName { get; set; }
        [JsonPropertyName("push_provider_type")]
        public string? PushProviderType { get; set; }
        [JsonPropertyName("skip_devices")]
        public bool? SkipDevices { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class CheckRequest
    {
        [JsonPropertyName("config_key")]
        public string ConfigKey { get; set; }
        [JsonPropertyName("entity_creator_id")]
        public string EntityCreatorID { get; set; }
        [JsonPropertyName("entity_id")]
        public string EntityID { get; set; }
        [JsonPropertyName("entity_type")]
        public string EntityType { get; set; }
        [JsonPropertyName("config_team")]
        public string? ConfigTeam { get; set; }
        [JsonPropertyName("test_mode")]
        public bool? TestMode { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("moderation_payload")]
        public ModerationPayload? ModerationPayload { get; set; }
        [JsonPropertyName("options")]
        public object Options { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class CheckSNSRequest
    {
        [JsonPropertyName("sns_key")]
        public string? SnsKey { get; set; }
        [JsonPropertyName("sns_secret")]
        public string? SnsSecret { get; set; }
        [JsonPropertyName("sns_topic_arn")]
        public string? SnsTopicArn { get; set; }
    }
    public class CheckSQSRequest
    {
        [JsonPropertyName("sqs_key")]
        public string? SqsKey { get; set; }
        [JsonPropertyName("sqs_secret")]
        public string? SqsSecret { get; set; }
        [JsonPropertyName("sqs_url")]
        public string? SqsUrl { get; set; }
    }
    public class CreateBlockListRequest
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }
        [JsonPropertyName("words")]
        public List<string> Words { get; set; }
        [JsonPropertyName("team")]
        public string? Team { get; set; }
        [JsonPropertyName("type")]
        public string? Type { get; set; }
    }
    public class CreateDeviceRequest
    {
        [JsonPropertyName("id")]
        public string ID { get; set; }
        [JsonPropertyName("push_provider")]
        public string PushProvider { get; set; }
        [JsonPropertyName("push_provider_name")]
        public string? PushProviderName { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("voip_token")]
        public bool? VoipToken { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class CreateExternalStorageRequest
    {
        [JsonPropertyName("bucket")]
        public string Bucket { get; set; }
        [JsonPropertyName("name")]
        public string Name { get; set; }
        [JsonPropertyName("storage_type")]
        public string StorageType { get; set; }
        [JsonPropertyName("gcs_credentials")]
        public string? GcsCredentials { get; set; }
        [JsonPropertyName("path")]
        public string? Path { get; set; }
        [JsonPropertyName("aws_s3")]
        public S3Request? AWSS3 { get; set; }
        [JsonPropertyName("azure_blob")]
        public AzureRequest? AzureBlob { get; set; }
    }
    public class CreateFeedGroupRequest
    {
        [JsonPropertyName("id")]
        public string ID { get; set; }
        [JsonPropertyName("default_visibility")]
        public string? DefaultVisibility { get; set; }
        [JsonPropertyName("activity_processors")]
        public List<ActivityProcessorConfig> ActivityProcessors { get; set; }
        [JsonPropertyName("activity_selectors")]
        public List<ActivitySelectorConfig> ActivitySelectors { get; set; }
        [JsonPropertyName("aggregation")]
        public AggregationConfig? Aggregation { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("notification")]
        public NotificationConfig? Notification { get; set; }
        [JsonPropertyName("ranking")]
        public RankingConfig? Ranking { get; set; }
    }
    public class CreateFeedViewRequest
    {
        [JsonPropertyName("id")]
        public string ID { get; set; }
        [JsonPropertyName("activity_processors")]
        public List<ActivityProcessorConfig> ActivityProcessors { get; set; }
        [JsonPropertyName("activity_selectors")]
        public List<ActivitySelectorConfig> ActivitySelectors { get; set; }
        [JsonPropertyName("aggregation")]
        public AggregationConfig? Aggregation { get; set; }
        [JsonPropertyName("ranking")]
        public RankingConfig? Ranking { get; set; }
    }
    public class CreateFeedsBatchRequest
    {
        [JsonPropertyName("feeds")]
        public List<FeedRequest> Feeds { get; set; }
    }
    public class CreateGuestRequest
    {
        [JsonPropertyName("user")]
        public UserRequest User { get; set; }
    }
    public class CreateImportRequest
    {
        [JsonPropertyName("mode")]
        public string Mode { get; set; }
        [JsonPropertyName("path")]
        public string Path { get; set; }
    }
    public class CreateImportURLRequest
    {
        [JsonPropertyName("filename")]
        public string? Filename { get; set; }
    }
    public class CreateMembershipLevelRequest
    {
        [JsonPropertyName("id")]
        public string ID { get; set; }
        [JsonPropertyName("name")]
        public string Name { get; set; }
        [JsonPropertyName("description")]
        public string? Description { get; set; }
        [JsonPropertyName("priority")]
        public int? Priority { get; set; }
        [JsonPropertyName("tags")]
        public List<string> Tags { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
    }
    public class CreatePollOptionRequest
    {
        [JsonPropertyName("text")]
        public string Text { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("Custom")]
        public object Custom { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class CreatePollRequest
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }
        [JsonPropertyName("allow_answers")]
        public bool? AllowAnswers { get; set; }
        [JsonPropertyName("allow_user_suggested_options")]
        public bool? AllowUserSuggestedOptions { get; set; }
        [JsonPropertyName("description")]
        public string? Description { get; set; }
        [JsonPropertyName("enforce_unique_vote")]
        public bool? EnforceUniqueVote { get; set; }
        [JsonPropertyName("id")]
        public string? ID { get; set; }
        [JsonPropertyName("is_closed")]
        public bool? IsClosed { get; set; }
        [JsonPropertyName("max_votes_allowed")]
        public int? MaxVotesAllowed { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("voting_visibility")]
        public string? VotingVisibility { get; set; }
        [JsonPropertyName("options")]
        public List<PollOptionInput> Options { get; set; }
        [JsonPropertyName("Custom")]
        public object Custom { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class CreateRoleRequest
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }
    }
    public class CustomCheckRequest
    {
        [JsonPropertyName("entity_id")]
        public string EntityID { get; set; }
        [JsonPropertyName("entity_type")]
        public string EntityType { get; set; }
        [JsonPropertyName("flags")]
        public List<CustomCheckFlag> Flags { get; set; }
        [JsonPropertyName("entity_creator_id")]
        public string? EntityCreatorID { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("moderation_payload")]
        public ModerationPayload? ModerationPayload { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class DeactivateUserRequest
    {
        [JsonPropertyName("created_by_id")]
        public string? CreatedByID { get; set; }
        [JsonPropertyName("mark_messages_deleted")]
        public bool? MarkMessagesDeleted { get; set; }
    }
    public class DeactivateUsersRequest
    {
        [JsonPropertyName("user_ids")]
        public List<string> UserIds { get; set; }
        [JsonPropertyName("created_by_id")]
        public string? CreatedByID { get; set; }
        [JsonPropertyName("mark_channels_deleted")]
        public bool? MarkChannelsDeleted { get; set; }
        [JsonPropertyName("mark_messages_deleted")]
        public bool? MarkMessagesDeleted { get; set; }
    }
    public class DeleteActivitiesRequest
    {
        [JsonPropertyName("ids")]
        public List<string> Ids { get; set; }
        [JsonPropertyName("hard_delete")]
        public bool? HardDelete { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class DeleteUsersRequest
    {
        [JsonPropertyName("user_ids")]
        public List<string> UserIds { get; set; }
        [JsonPropertyName("calls")]
        public string? Calls { get; set; }
        [JsonPropertyName("conversations")]
        public string? Conversations { get; set; }
        [JsonPropertyName("files")]
        public bool? Files { get; set; }
        [JsonPropertyName("messages")]
        public string? Messages { get; set; }
        [JsonPropertyName("new_call_owner_id")]
        public string? NewCallOwnerID { get; set; }
        [JsonPropertyName("new_channel_owner_id")]
        public string? NewChannelOwnerID { get; set; }
        [JsonPropertyName("user")]
        public string? User { get; set; }
    }
    public class ExportFeedUserDataRequest
    {
        [JsonPropertyName("id")]
        public string ID { get; set; }
        [JsonPropertyName("image")]
        public string? Image { get; set; }
        [JsonPropertyName("invisible")]
        public bool? Invisible { get; set; }
        [JsonPropertyName("language")]
        public string? Language { get; set; }
        [JsonPropertyName("name")]
        public string? Name { get; set; }
        [JsonPropertyName("role")]
        public string? Role { get; set; }
        [JsonPropertyName("teams")]
        public List<string> Teams { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("privacy_settings")]
        public PrivacySettingsResponse? PrivacySettings { get; set; }
        [JsonPropertyName("teams_role")]
        public Dictionary<string, string> TeamsRole { get; set; }
    }
    public class ExportUsersRequest
    {
        [JsonPropertyName("user_ids")]
        public List<string> UserIds { get; set; }
    }
    public class FileUploadRequest
    {
        [JsonPropertyName("file")]
        public string? File { get; set; }
        [JsonPropertyName("user")]
        public OnlyUserID? User { get; set; }
    }
    public class FlagRequest
    {
        [JsonPropertyName("entity_id")]
        public string EntityID { get; set; }
        [JsonPropertyName("entity_type")]
        public string EntityType { get; set; }
        [JsonPropertyName("entity_creator_id")]
        public string? EntityCreatorID { get; set; }
        [JsonPropertyName("reason")]
        public string? Reason { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("moderation_payload")]
        public ModerationPayload? ModerationPayload { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class FollowBatchRequest
    {
        [JsonPropertyName("follows")]
        public List<FollowRequest> Follows { get; set; }
    }
    public class FollowRequest
    {
        [JsonPropertyName("source")]
        public string Source { get; set; }
        [JsonPropertyName("target")]
        public string Target { get; set; }
        [JsonPropertyName("create_notification_activity")]
        public bool? CreateNotificationActivity { get; set; }
        [JsonPropertyName("push_preference")]
        public string? PushPreference { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
    }
    public class GetOrCreateFeedGroupRequest
    {
        [JsonPropertyName("default_visibility")]
        public string? DefaultVisibility { get; set; }
        [JsonPropertyName("activity_processors")]
        public List<ActivityProcessorConfig> ActivityProcessors { get; set; }
        [JsonPropertyName("activity_selectors")]
        public List<ActivitySelectorConfig> ActivitySelectors { get; set; }
        [JsonPropertyName("aggregation")]
        public AggregationConfig? Aggregation { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("notification")]
        public NotificationConfig? Notification { get; set; }
        [JsonPropertyName("ranking")]
        public RankingConfig? Ranking { get; set; }
    }
    public class GetOrCreateFeedRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("view")]
        public string? View { get; set; }
        [JsonPropertyName("watch")]
        public bool? Watch { get; set; }
        [JsonPropertyName("activity_selector_options")]
        public object ActivitySelectorOptions { get; set; }
        [JsonPropertyName("data")]
        public FeedInput? Data { get; set; }
        [JsonPropertyName("external_ranking")]
        public object ExternalRanking { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
        [JsonPropertyName("followers_pagination")]
        public PagerRequest? FollowersPagination { get; set; }
        [JsonPropertyName("following_pagination")]
        public PagerRequest? FollowingPagination { get; set; }
        [JsonPropertyName("interest_weights")]
        public Dictionary<string, double> InterestWeights { get; set; }
        [JsonPropertyName("member_pagination")]
        public PagerRequest? MemberPagination { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class GetOrCreateFeedViewRequest
    {
        [JsonPropertyName("activity_processors")]
        public List<ActivityProcessorConfig> ActivityProcessors { get; set; }
        [JsonPropertyName("activity_selectors")]
        public List<ActivitySelectorConfig> ActivitySelectors { get; set; }
        [JsonPropertyName("aggregation")]
        public AggregationConfig? Aggregation { get; set; }
        [JsonPropertyName("ranking")]
        public RankingConfig? Ranking { get; set; }
    }
    public class ImageUploadRequest
    {
        [JsonPropertyName("file")]
        public string? File { get; set; }
        [JsonPropertyName("upload_sizes")]
        public List<ImageSize> UploadSizes { get; set; }
        [JsonPropertyName("user")]
        public OnlyUserID? User { get; set; }
    }
    public class MarkActivityRequest
    {
        [JsonPropertyName("mark_all_read")]
        public bool? MarkAllRead { get; set; }
        [JsonPropertyName("mark_all_seen")]
        public bool? MarkAllSeen { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("mark_read")]
        public List<string> MarkRead { get; set; }
        [JsonPropertyName("mark_seen")]
        public List<string> MarkSeen { get; set; }
        [JsonPropertyName("mark_watched")]
        public List<string> MarkWatched { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class MuteRequest
    {
        [JsonPropertyName("target_ids")]
        public List<string> TargetIds { get; set; }
        [JsonPropertyName("timeout")]
        public int? Timeout { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class PinActivityRequest
    {
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class QueryActivitiesRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryActivityReactionsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryBookmarkFoldersRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryBookmarksRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryCommentReactionsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryCommentsRequest
    {
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public string? Sort { get; set; }
    }
    public class QueryFeedMembersRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryFeedsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("watch")]
        public bool? Watch { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryFollowsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryMembershipLevelsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryModerationConfigsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class QueryModerationFlagsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParam> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryModerationLogsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class QueryPollVotesRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryPollsRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
    }
    public class QueryReviewQueueRequest
    {
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("lock_count")]
        public int? LockCount { get; set; }
        [JsonPropertyName("lock_duration")]
        public int? LockDuration { get; set; }
        [JsonPropertyName("lock_items")]
        public bool? LockItems { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("stats_only")]
        public bool? StatsOnly { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("sort")]
        public List<SortParamRequest> Sort { get; set; }
        [JsonPropertyName("filter")]
        public object Filter { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class ReactivateUserRequest
    {
        [JsonPropertyName("created_by_id")]
        public string? CreatedByID { get; set; }
        [JsonPropertyName("name")]
        public string? Name { get; set; }
        [JsonPropertyName("restore_messages")]
        public bool? RestoreMessages { get; set; }
    }
    public class ReactivateUsersRequest
    {
        [JsonPropertyName("user_ids")]
        public List<string> UserIds { get; set; }
        [JsonPropertyName("created_by_id")]
        public string? CreatedByID { get; set; }
        [JsonPropertyName("restore_channels")]
        public bool? RestoreChannels { get; set; }
        [JsonPropertyName("restore_messages")]
        public bool? RestoreMessages { get; set; }
    }
    public class RejectFeedMemberInviteRequest
    {
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class RejectFollowRequest
    {
        [JsonPropertyName("source")]
        public string Source { get; set; }
        [JsonPropertyName("target")]
        public string Target { get; set; }
    }
    public class RestoreUsersRequest
    {
        [JsonPropertyName("user_ids")]
        public List<string> UserIds { get; set; }
    }
    public class SubmitActionRequest
    {
        [JsonPropertyName("action_type")]
        public string ActionType { get; set; }
        [JsonPropertyName("item_id")]
        public string ItemID { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("ban")]
        public BanActionRequest? Ban { get; set; }
        [JsonPropertyName("custom")]
        public CustomActionRequest? Custom { get; set; }
        // [JsonPropertyName("delete_activity")]
        // public DeleteActivityRequest? DeleteActivity { get; set; }
        // [JsonPropertyName("delete_message")]
        // public DeleteMessageRequest? DeleteMessage { get; set; }
        // [JsonPropertyName("delete_reaction")]
        // public DeleteReactionRequest? DeleteReaction { get; set; }
        [JsonPropertyName("delete_user")]
        public DeleteUserRequest? DeleteUser { get; set; }
        [JsonPropertyName("mark_reviewed")]
        public MarkReviewedRequest? MarkReviewed { get; set; }
        [JsonPropertyName("unban")]
        public UnbanActionRequest? Unban { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UnbanRequest
    {
        [JsonPropertyName("unbanned_by_id")]
        public string? UnbannedByID { get; set; }
        [JsonPropertyName("unbanned_by")]
        public UserRequest? UnbannedBy { get; set; }
    }
    public class UnblockUsersRequest
    {
        [JsonPropertyName("blocked_user_id")]
        public string BlockedUserID { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UnfollowBatchRequest
    {
        [JsonPropertyName("follows")]
        public List<FollowPair> Follows { get; set; }
    }
    public class UnmuteRequest
    {
        [JsonPropertyName("target_ids")]
        public List<string> TargetIds { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UpdateActivityPartialRequest
    {
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("unset")]
        public List<string> Unset { get; set; }
        [JsonPropertyName("set")]
        public object Set { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UpdateActivityRequest
    {
        [JsonPropertyName("expires_at")]
        public DateTime? ExpiresAt { get; set; }
        [JsonPropertyName("poll_id")]
        public string? PollID { get; set; }
        [JsonPropertyName("text")]
        public string? Text { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("visibility")]
        public string? Visibility { get; set; }
        [JsonPropertyName("attachments")]
        public List<Attachment> Attachments { get; set; }
        [JsonPropertyName("filter_tags")]
        public List<string> FilterTags { get; set; }
        [JsonPropertyName("interest_tags")]
        public List<string> InterestTags { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("location")]
        public ActivityLocation? Location { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UpdateAppRequest
    {
        [JsonPropertyName("async_url_enrich_enabled")]
        public bool? AsyncUrlEnrichEnabled { get; set; }
        [JsonPropertyName("auto_translation_enabled")]
        public bool? AutoTranslationEnabled { get; set; }
        [JsonPropertyName("before_message_send_hook_url")]
        public string? BeforeMessageSendHookUrl { get; set; }
        [JsonPropertyName("cdn_expiration_seconds")]
        public int? CdnExpirationSeconds { get; set; }
        [JsonPropertyName("channel_hide_members_only")]
        public bool? ChannelHideMembersOnly { get; set; }
        [JsonPropertyName("custom_action_handler_url")]
        public string? CustomActionHandlerUrl { get; set; }
        [JsonPropertyName("disable_auth_checks")]
        public bool? DisableAuthChecks { get; set; }
        [JsonPropertyName("disable_permissions_checks")]
        public bool? DisablePermissionsChecks { get; set; }
        [JsonPropertyName("enforce_unique_usernames")]
        public string? EnforceUniqueUsernames { get; set; }
        [JsonPropertyName("feeds_moderation_enabled")]
        public bool? FeedsModerationEnabled { get; set; }
        [JsonPropertyName("feeds_v2_region")]
        public string? FeedsV2Region { get; set; }
        [JsonPropertyName("guest_user_creation_disabled")]
        public bool? GuestUserCreationDisabled { get; set; }
        [JsonPropertyName("image_moderation_enabled")]
        public bool? ImageModerationEnabled { get; set; }
        [JsonPropertyName("max_aggregated_activities_length")]
        public int? MaxAggregatedActivitiesLength { get; set; }
        [JsonPropertyName("migrate_permissions_to_v2")]
        public bool? MigratePermissionsToV2 { get; set; }
        [JsonPropertyName("moderation_enabled")]
        public bool? ModerationEnabled { get; set; }
        [JsonPropertyName("moderation_webhook_url")]
        public string? ModerationWebhookUrl { get; set; }
        [JsonPropertyName("multi_tenant_enabled")]
        public bool? MultiTenantEnabled { get; set; }
        [JsonPropertyName("permission_version")]
        public string? PermissionVersion { get; set; }
        [JsonPropertyName("reminders_interval")]
        public int? RemindersInterval { get; set; }
        [JsonPropertyName("reminders_max_members")]
        public int? RemindersMaxMembers { get; set; }
        [JsonPropertyName("revoke_tokens_issued_before")]
        public DateTime? RevokeTokensIssuedBefore { get; set; }
        [JsonPropertyName("sns_key")]
        public string? SnsKey { get; set; }
        [JsonPropertyName("sns_secret")]
        public string? SnsSecret { get; set; }
        [JsonPropertyName("sns_topic_arn")]
        public string? SnsTopicArn { get; set; }
        [JsonPropertyName("sqs_key")]
        public string? SqsKey { get; set; }
        [JsonPropertyName("sqs_secret")]
        public string? SqsSecret { get; set; }
        [JsonPropertyName("sqs_url")]
        public string? SqsUrl { get; set; }
        [JsonPropertyName("user_response_time_enabled")]
        public bool? UserResponseTimeEnabled { get; set; }
        [JsonPropertyName("webhook_url")]
        public string? WebhookUrl { get; set; }
        [JsonPropertyName("allowed_flag_reasons")]
        public List<string> AllowedFlagReasons { get; set; }
        [JsonPropertyName("event_hooks")]
        public List<EventHook> EventHooks { get; set; }
        [JsonPropertyName("image_moderation_block_labels")]
        public List<string> ImageModerationBlockLabels { get; set; }
        [JsonPropertyName("image_moderation_labels")]
        public List<string> ImageModerationLabels { get; set; }
        [JsonPropertyName("user_search_disallowed_roles")]
        public List<string> UserSearchDisallowedRoles { get; set; }
        [JsonPropertyName("webhook_events")]
        public List<string> WebhookEvents { get; set; }
        [JsonPropertyName("apn_config")]
        public APNConfig? ApnConfig { get; set; }
        [JsonPropertyName("async_moderation_config")]
        public AsyncModerationConfiguration? AsyncModerationConfig { get; set; }
        [JsonPropertyName("datadog_info")]
        public DataDogInfo? DatadogInfo { get; set; }
        [JsonPropertyName("file_upload_config")]
        public FileUploadConfig? FileUploadConfig { get; set; }
        [JsonPropertyName("firebase_config")]
        public FirebaseConfig? FirebaseConfig { get; set; }
        [JsonPropertyName("grants")]
        public Dictionary<string, List<string>> Grants { get; set; }
        [JsonPropertyName("huawei_config")]
        public HuaweiConfig? HuaweiConfig { get; set; }
        [JsonPropertyName("image_upload_config")]
        public FileUploadConfig? ImageUploadConfig { get; set; }
        [JsonPropertyName("moderation_dashboard_preferences")]
        public ModerationDashboardPreferences? ModerationDashboardPreferences { get; set; }
        [JsonPropertyName("push_config")]
        public PushConfig? PushConfig { get; set; }
        [JsonPropertyName("xiaomi_config")]
        public XiaomiConfig? XiaomiConfig { get; set; }
    }
    public class UpdateBlockListRequest
    {
        [JsonPropertyName("team")]
        public string? Team { get; set; }
        [JsonPropertyName("words")]
        public List<string> Words { get; set; }
    }
    public class UpdateBookmarkFolderRequest
    {
        [JsonPropertyName("name")]
        public string? Name { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UpdateBookmarkRequest
    {
        [JsonPropertyName("folder_id")]
        public string? FolderID { get; set; }
        [JsonPropertyName("new_folder_id")]
        public string? NewFolderID { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("new_folder")]
        public AddFolderRequest? NewFolder { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UpdateCommentRequest
    {
        [JsonPropertyName("comment")]
        public string? Comment { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
    }
    public class UpdateExternalStorageRequest
    {
        [JsonPropertyName("bucket")]
        public string Bucket { get; set; }
        [JsonPropertyName("storage_type")]
        public string StorageType { get; set; }
        [JsonPropertyName("gcs_credentials")]
        public string? GcsCredentials { get; set; }
        [JsonPropertyName("path")]
        public string? Path { get; set; }
        [JsonPropertyName("aws_s3")]
        public S3Request? AWSS3 { get; set; }
        [JsonPropertyName("azure_blob")]
        public AzureRequest? AzureBlob { get; set; }
    }
    public class UpdateFeedGroupRequest
    {
        [JsonPropertyName("activity_processors")]
        public List<ActivityProcessorConfig> ActivityProcessors { get; set; }
        [JsonPropertyName("activity_selectors")]
        public List<ActivitySelectorConfig> ActivitySelectors { get; set; }
        [JsonPropertyName("aggregation")]
        public AggregationConfig? Aggregation { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
        [JsonPropertyName("notification")]
        public NotificationConfig? Notification { get; set; }
        [JsonPropertyName("ranking")]
        public RankingConfig? Ranking { get; set; }
    }
    public class UpdateFeedMembersRequest
    {
        [JsonPropertyName("operation")]
        public string Operation { get; set; }
        [JsonPropertyName("limit")]
        public int? Limit { get; set; }
        [JsonPropertyName("next")]
        public string? Next { get; set; }
        [JsonPropertyName("prev")]
        public string? Prev { get; set; }
        [JsonPropertyName("members")]
        public List<FeedMemberRequest> Members { get; set; }
    }
    public class UpdateFeedRequest
    {
        [JsonPropertyName("created_by_id")]
        public string? CreatedByID { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
    }
    public class UpdateFeedViewRequest
    {
        [JsonPropertyName("activity_processors")]
        public List<ActivityProcessorConfig> ActivityProcessors { get; set; }
        [JsonPropertyName("activity_selectors")]
        public List<ActivitySelectorConfig> ActivitySelectors { get; set; }
        [JsonPropertyName("aggregation")]
        public AggregationConfig? Aggregation { get; set; }
        [JsonPropertyName("ranking")]
        public RankingConfig? Ranking { get; set; }
    }
    public class UpdateFollowRequest
    {
        [JsonPropertyName("source")]
        public string Source { get; set; }
        [JsonPropertyName("target")]
        public string Target { get; set; }
        [JsonPropertyName("create_notification_activity")]
        public bool? CreateNotificationActivity { get; set; }
        [JsonPropertyName("follower_role")]
        public string? FollowerRole { get; set; }
        [JsonPropertyName("push_preference")]
        public string? PushPreference { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
    }
    public class UpdateLiveLocationRequest
    {
        [JsonPropertyName("message_id")]
        public string MessageID { get; set; }
        [JsonPropertyName("end_at")]
        public DateTime? EndAt { get; set; }
        [JsonPropertyName("latitude")]
        public double? Latitude { get; set; }
        [JsonPropertyName("longitude")]
        public double? Longitude { get; set; }
    }
    public class UpdateMembershipLevelRequest
    {
        [JsonPropertyName("description")]
        public string? Description { get; set; }
        [JsonPropertyName("name")]
        public string? Name { get; set; }
        [JsonPropertyName("priority")]
        public int? Priority { get; set; }
        [JsonPropertyName("tags")]
        public List<string> Tags { get; set; }
        [JsonPropertyName("custom")]
        public object Custom { get; set; }
    }
    public class UpdatePollOptionRequest
    {
        [JsonPropertyName("id")]
        public string ID { get; set; }
        [JsonPropertyName("text")]
        public string Text { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("Custom")]
        public object Custom { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UpdatePollPartialRequest
    {
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("unset")]
        public List<string> Unset { get; set; }
        [JsonPropertyName("set")]
        public object Set { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UpdatePollRequest
    {
        [JsonPropertyName("id")]
        public string ID { get; set; }
        [JsonPropertyName("name")]
        public string Name { get; set; }
        [JsonPropertyName("allow_answers")]
        public bool? AllowAnswers { get; set; }
        [JsonPropertyName("allow_user_suggested_options")]
        public bool? AllowUserSuggestedOptions { get; set; }
        [JsonPropertyName("description")]
        public string? Description { get; set; }
        [JsonPropertyName("enforce_unique_vote")]
        public bool? EnforceUniqueVote { get; set; }
        [JsonPropertyName("is_closed")]
        public bool? IsClosed { get; set; }
        [JsonPropertyName("max_votes_allowed")]
        public int? MaxVotesAllowed { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("voting_visibility")]
        public string? VotingVisibility { get; set; }
        [JsonPropertyName("options")]
        public List<PollOptionRequest> Options { get; set; }
        [JsonPropertyName("Custom")]
        public object Custom { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
    }
    public class UpdateUsersPartialRequest
    {
        [JsonPropertyName("users")]
        public List<UpdateUserPartialRequest> Users { get; set; }
    }
    public class UpdateUsersRequest
    {
        [JsonPropertyName("users")]
        public Dictionary<string, UserRequest> Users { get; set; }
    }
    public class UpsertActivitiesRequest
    {
        [JsonPropertyName("activities")]
        public List<ActivityRequest> Activities { get; set; }
    }
    public class UpsertConfigRequest
    {
        [JsonPropertyName("key")]
        public string Key { get; set; }
        [JsonPropertyName("async")]
        public bool? Async { get; set; }
        [JsonPropertyName("team")]
        public string? Team { get; set; }
        [JsonPropertyName("user_id")]
        public string? UserID { get; set; }
        [JsonPropertyName("aws_rekognition_config")]
        public AIImageConfig? AWSRekognitionConfig { get; set; }
        [JsonPropertyName("ai_image_config")]
        public AIImageConfig? AiImageConfig { get; set; }
        [JsonPropertyName("ai_text_config")]
        public AITextConfig? AiTextConfig { get; set; }
        [JsonPropertyName("ai_video_config")]
        public AIVideoConfig? AiVideoConfig { get; set; }
        [JsonPropertyName("automod_platform_circumvention_config")]
        public AutomodPlatformCircumventionConfig? AutomodPlatformCircumventionConfig { get; set; }
        [JsonPropertyName("automod_semantic_filters_config")]
        public AutomodSemanticFiltersConfig? AutomodSemanticFiltersConfig { get; set; }
        [JsonPropertyName("automod_toxicity_config")]
        public AutomodToxicityConfig? AutomodToxicityConfig { get; set; }
        [JsonPropertyName("block_list_config")]
        public BlockListConfig? BlockListConfig { get; set; }
        [JsonPropertyName("bodyguard_config")]
        public AITextConfig? BodyguardConfig { get; set; }
        [JsonPropertyName("google_vision_config")]
        public GoogleVisionConfig? GoogleVisionConfig { get; set; }
        [JsonPropertyName("llm_config")]
        public LLMConfig? LlmConfig { get; set; }
        [JsonPropertyName("rule_builder_config")]
        public RuleBuilderConfig? RuleBuilderConfig { get; set; }
        [JsonPropertyName("user")]
        public UserRequest? User { get; set; }
        [JsonPropertyName("velocity_filter_config")]
        public VelocityFilterConfig? VelocityFilterConfig { get; set; }
        [JsonPropertyName("video_call_rule_config")]
        public VideoCallRuleConfig? VideoCallRuleConfig { get; set; }
    }
    public class UpsertModerationTemplateRequest
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }
        [JsonPropertyName("config")]
        public FeedsModerationTemplateConfig Config { get; set; }
    }
    public class UpsertPushProviderRequest
    {
        [JsonPropertyName("push_provider")]
        public PushProvider? PushProvider { get; set; }
    }
} 
