// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

using System;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using GetStream.Models;

namespace GetStream
{
    /// <summary>
    /// Webhook event type constants.
    /// </summary>
    public static class WebhookEventType
    {
        public const string Wildcard = "*";
        public const string AppealAccepted = "appeal.accepted";
        public const string AppealCreated = "appeal.created";
        public const string AppealRejected = "appeal.rejected";
        public const string CallAccepted = "call.accepted";
        public const string CallBlockedUser = "call.blocked_user";
        public const string CallClosedCaption = "call.closed_caption";
        public const string CallClosedCaptionsFailed = "call.closed_captions_failed";
        public const string CallClosedCaptionsStarted = "call.closed_captions_started";
        public const string CallClosedCaptionsStopped = "call.closed_captions_stopped";
        public const string CallCreated = "call.created";
        public const string CallDeleted = "call.deleted";
        public const string CallDtmf = "call.dtmf";
        public const string CallEnded = "call.ended";
        public const string CallFrameRecordingFailed = "call.frame_recording_failed";
        public const string CallFrameRecordingReady = "call.frame_recording_ready";
        public const string CallFrameRecordingStarted = "call.frame_recording_started";
        public const string CallFrameRecordingStopped = "call.frame_recording_stopped";
        public const string CallHLSBroadcastingFailed = "call.hls_broadcasting_failed";
        public const string CallHLSBroadcastingStarted = "call.hls_broadcasting_started";
        public const string CallHLSBroadcastingStopped = "call.hls_broadcasting_stopped";
        public const string CallKickedUser = "call.kicked_user";
        public const string CallLiveStarted = "call.live_started";
        public const string CallMemberAdded = "call.member_added";
        public const string CallMemberRemoved = "call.member_removed";
        public const string CallMemberUpdated = "call.member_updated";
        public const string CallMemberUpdatedPermission = "call.member_updated_permission";
        public const string CallMissed = "call.missed";
        public const string CallModerationBlur = "call.moderation_blur";
        public const string CallModerationWarning = "call.moderation_warning";
        public const string CallNotification = "call.notification";
        public const string CallPermissionRequest = "call.permission_request";
        public const string CallPermissionsUpdated = "call.permissions_updated";
        public const string CallReactionNew = "call.reaction_new";
        public const string CallRecordingFailed = "call.recording_failed";
        public const string CallRecordingReady = "call.recording_ready";
        public const string CallRecordingStarted = "call.recording_started";
        public const string CallRecordingStopped = "call.recording_stopped";
        public const string CallRejected = "call.rejected";
        public const string CallRing = "call.ring";
        public const string CallRTMPBroadcastFailed = "call.rtmp_broadcast_failed";
        public const string CallRTMPBroadcastStarted = "call.rtmp_broadcast_started";
        public const string CallRTMPBroadcastStopped = "call.rtmp_broadcast_stopped";
        public const string CallSessionEnded = "call.session_ended";
        public const string CallSessionParticipantCountUpdated = "call.session_participant_count_updated";
        public const string CallSessionParticipantJoined = "call.session_participant_joined";
        public const string CallSessionParticipantLeft = "call.session_participant_left";
        public const string CallSessionStarted = "call.session_started";
        public const string CallStatsReportReady = "call.stats_report_ready";
        public const string CallTranscriptionFailed = "call.transcription_failed";
        public const string CallTranscriptionReady = "call.transcription_ready";
        public const string CallTranscriptionStarted = "call.transcription_started";
        public const string CallTranscriptionStopped = "call.transcription_stopped";
        public const string CallUnblockedUser = "call.unblocked_user";
        public const string CallUpdated = "call.updated";
        public const string CallUserFeedbackSubmitted = "call.user_feedback_submitted";
        public const string CallUserMuted = "call.user_muted";
        public const string CampaignCompleted = "campaign.completed";
        public const string CampaignStarted = "campaign.started";
        public const string ChannelCreated = "channel.created";
        public const string ChannelDeleted = "channel.deleted";
        public const string ChannelFrozen = "channel.frozen";
        public const string ChannelHidden = "channel.hidden";
        public const string ChannelMaxStreakChanged = "channel.max_streak_changed";
        public const string ChannelMuted = "channel.muted";
        public const string ChannelTruncated = "channel.truncated";
        public const string ChannelUnfrozen = "channel.unfrozen";
        public const string ChannelUnmuted = "channel.unmuted";
        public const string ChannelUpdated = "channel.updated";
        public const string ChannelVisible = "channel.visible";
        public const string ChannelBatchUpdateCompleted = "channel_batch_update.completed";
        public const string ChannelBatchUpdateStarted = "channel_batch_update.started";
        public const string Custom = "custom";
        public const string ExportBulkImageModerationError = "export.bulk_image_moderation.error";
        public const string ExportBulkImageModerationSuccess = "export.bulk_image_moderation.success";
        public const string ExportChannelsError = "export.channels.error";
        public const string ExportChannelsSuccess = "export.channels.success";
        public const string ExportModerationLogsError = "export.moderation_logs.error";
        public const string ExportModerationLogsSuccess = "export.moderation_logs.success";
        public const string ExportUsersError = "export.users.error";
        public const string ExportUsersSuccess = "export.users.success";
        public const string FeedsActivityAdded = "feeds.activity.added";
        public const string FeedsActivityDeleted = "feeds.activity.deleted";
        public const string FeedsActivityFeedback = "feeds.activity.feedback";
        public const string FeedsActivityMarked = "feeds.activity.marked";
        public const string FeedsActivityPinned = "feeds.activity.pinned";
        public const string FeedsActivityReactionAdded = "feeds.activity.reaction.added";
        public const string FeedsActivityReactionDeleted = "feeds.activity.reaction.deleted";
        public const string FeedsActivityReactionUpdated = "feeds.activity.reaction.updated";
        public const string FeedsActivityRemovedFromFeed = "feeds.activity.removed_from_feed";
        public const string FeedsActivityRestored = "feeds.activity.restored";
        public const string FeedsActivityUnpinned = "feeds.activity.unpinned";
        public const string FeedsActivityUpdated = "feeds.activity.updated";
        public const string FeedsBookmarkAdded = "feeds.bookmark.added";
        public const string FeedsBookmarkDeleted = "feeds.bookmark.deleted";
        public const string FeedsBookmarkUpdated = "feeds.bookmark.updated";
        public const string FeedsBookmarkFolderDeleted = "feeds.bookmark_folder.deleted";
        public const string FeedsBookmarkFolderUpdated = "feeds.bookmark_folder.updated";
        public const string FeedsCommentAdded = "feeds.comment.added";
        public const string FeedsCommentDeleted = "feeds.comment.deleted";
        public const string FeedsCommentReactionAdded = "feeds.comment.reaction.added";
        public const string FeedsCommentReactionDeleted = "feeds.comment.reaction.deleted";
        public const string FeedsCommentReactionUpdated = "feeds.comment.reaction.updated";
        public const string FeedsCommentRestored = "feeds.comment.restored";
        public const string FeedsCommentUpdated = "feeds.comment.updated";
        public const string FeedsFeedCreated = "feeds.feed.created";
        public const string FeedsFeedDeleted = "feeds.feed.deleted";
        public const string FeedsFeedUpdated = "feeds.feed.updated";
        public const string FeedsFeedGroupChanged = "feeds.feed_group.changed";
        public const string FeedsFeedGroupDeleted = "feeds.feed_group.deleted";
        public const string FeedsFeedGroupRestored = "feeds.feed_group.restored";
        public const string FeedsFeedMemberAdded = "feeds.feed_member.added";
        public const string FeedsFeedMemberRemoved = "feeds.feed_member.removed";
        public const string FeedsFeedMemberUpdated = "feeds.feed_member.updated";
        public const string FeedsFollowCreated = "feeds.follow.created";
        public const string FeedsFollowDeleted = "feeds.follow.deleted";
        public const string FeedsFollowUpdated = "feeds.follow.updated";
        public const string FeedsNotificationFeedUpdated = "feeds.notification_feed.updated";
        public const string FeedsStoriesFeedUpdated = "feeds.stories_feed.updated";
        public const string FlagUpdated = "flag.updated";
        public const string IngressError = "ingress.error";
        public const string IngressStarted = "ingress.started";
        public const string IngressStopped = "ingress.stopped";
        public const string MemberAdded = "member.added";
        public const string MemberRemoved = "member.removed";
        public const string MemberUpdated = "member.updated";
        public const string MessageDeleted = "message.deleted";
        public const string MessageFlagged = "message.flagged";
        public const string MessageNew = "message.new";
        public const string MessagePending = "message.pending";
        public const string MessageRead = "message.read";
        public const string MessageUnblocked = "message.unblocked";
        public const string MessageUndeleted = "message.undeleted";
        public const string MessageUpdated = "message.updated";
        public const string ModerationCustomAction = "moderation.custom_action";
        public const string ModerationFlagged = "moderation.flagged";
        public const string ModerationMarkReviewed = "moderation.mark_reviewed";
        public const string ModerationCheckCompleted = "moderation_check.completed";
        public const string ModerationRuleTriggered = "moderation_rule.triggered";
        public const string NotificationMarkUnread = "notification.mark_unread";
        public const string NotificationReminderDue = "notification.reminder_due";
        public const string NotificationThreadMessageNew = "notification.thread_message_new";
        public const string ReactionDeleted = "reaction.deleted";
        public const string ReactionNew = "reaction.new";
        public const string ReactionUpdated = "reaction.updated";
        public const string ReminderCreated = "reminder.created";
        public const string ReminderDeleted = "reminder.deleted";
        public const string ReminderUpdated = "reminder.updated";
        public const string ReviewQueueItemNew = "review_queue_item.new";
        public const string ReviewQueueItemUpdated = "review_queue_item.updated";
        public const string ThreadUpdated = "thread.updated";
        public const string UserBanned = "user.banned";
        public const string UserDeactivated = "user.deactivated";
        public const string UserDeleted = "user.deleted";
        public const string UserFlagged = "user.flagged";
        public const string UserMessagesDeleted = "user.messages.deleted";
        public const string UserMuted = "user.muted";
        public const string UserReactivated = "user.reactivated";
        public const string UserUnbanned = "user.unbanned";
        public const string UserUnmuted = "user.unmuted";
        public const string UserUnreadMessageReminder = "user.unread_message_reminder";
        public const string UserUpdated = "user.updated";
        public const string UserGroupCreated = "user_group.created";
        public const string UserGroupDeleted = "user_group.deleted";
        public const string UserGroupMemberAdded = "user_group.member_added";
        public const string UserGroupMemberRemoved = "user_group.member_removed";
        public const string UserGroupUpdated = "user_group.updated";
    }

    /// <summary>
    /// Webhook utilities for Stream webhooks.
    /// </summary>
    public static class Webhook
    {
        /// <summary>
        /// Extract the event type from a raw webhook payload.
        /// </summary>
        /// <param name="rawEvent">The raw webhook payload as a byte array</param>
        /// <returns>The event type string (e.g., "message.new"), or null if not found</returns>
        public static string GetEventType(byte[] rawEvent)
        {
            try
            {
                using var doc = JsonDocument.Parse(rawEvent);
                if (doc.RootElement.TryGetProperty("type", out var typeElement))
                {
                    return typeElement.GetString();
                }
                return null;
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Extract the event type from a raw webhook payload.
        /// </summary>
        /// <param name="rawEvent">The raw webhook payload as a string</param>
        /// <returns>The event type string (e.g., "message.new"), or null if not found</returns>
        public static string GetEventType(string rawEvent)
        {
            return GetEventType(Encoding.UTF8.GetBytes(rawEvent));
        }

        /// <summary>
        /// Deserialize a raw webhook payload into a typed event object.
        /// </summary>
        /// <param name="rawEvent">The raw webhook payload as a byte array</param>
        /// <returns>A typed event object corresponding to the event type</returns>
        /// <exception cref="WebhookException">Thrown if the event type is unknown or deserialization fails</exception>
        public static object ParseWebhookEvent(byte[] rawEvent)
        {
            var eventType = GetEventType(rawEvent);
            if (string.IsNullOrEmpty(eventType))
            {
                throw new WebhookException("Webhook payload missing 'type' field");
            }

            var eventClass = GetEventTypeClass(eventType);
            if (eventClass == null)
            {
                throw new WebhookException($"Unknown webhook event type: {eventType}");
            }

            try
            {
                return JsonSerializer.Deserialize(rawEvent, eventClass);
            }
            catch (Exception ex)
            {
                throw new WebhookException($"Failed to deserialize webhook event: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Deserialize a raw webhook payload into a typed event object.
        /// </summary>
        /// <param name="rawEvent">The raw webhook payload as a string</param>
        /// <returns>A typed event object corresponding to the event type</returns>
        /// <exception cref="WebhookException">Thrown if the event type is unknown or deserialization fails</exception>
        public static object ParseWebhookEvent(string rawEvent)
        {
            return ParseWebhookEvent(Encoding.UTF8.GetBytes(rawEvent));
        }

        private static Type GetEventTypeClass(string eventType)
        {
            return eventType switch
            {
                "*" => typeof(CustomEvent),
                "appeal.accepted" => typeof(AppealAcceptedEvent),
                "appeal.created" => typeof(AppealCreatedEvent),
                "appeal.rejected" => typeof(AppealRejectedEvent),
                "call.accepted" => typeof(CallAcceptedEvent),
                "call.blocked_user" => typeof(BlockedUserEvent),
                "call.closed_caption" => typeof(ClosedCaptionEvent),
                "call.closed_captions_failed" => typeof(CallClosedCaptionsFailedEvent),
                "call.closed_captions_started" => typeof(CallClosedCaptionsStartedEvent),
                "call.closed_captions_stopped" => typeof(CallClosedCaptionsStoppedEvent),
                "call.created" => typeof(CallCreatedEvent),
                "call.deleted" => typeof(CallDeletedEvent),
                "call.dtmf" => typeof(CallDTMFEvent),
                "call.ended" => typeof(CallEndedEvent),
                "call.frame_recording_failed" => typeof(CallFrameRecordingFailedEvent),
                "call.frame_recording_ready" => typeof(CallFrameRecordingFrameReadyEvent),
                "call.frame_recording_started" => typeof(CallFrameRecordingStartedEvent),
                "call.frame_recording_stopped" => typeof(CallFrameRecordingStoppedEvent),
                "call.hls_broadcasting_failed" => typeof(CallHLSBroadcastingFailedEvent),
                "call.hls_broadcasting_started" => typeof(CallHLSBroadcastingStartedEvent),
                "call.hls_broadcasting_stopped" => typeof(CallHLSBroadcastingStoppedEvent),
                "call.kicked_user" => typeof(KickedUserEvent),
                "call.live_started" => typeof(CallLiveStartedEvent),
                "call.member_added" => typeof(CallMemberAddedEvent),
                "call.member_removed" => typeof(CallMemberRemovedEvent),
                "call.member_updated" => typeof(CallMemberUpdatedEvent),
                "call.member_updated_permission" => typeof(CallMemberUpdatedPermissionEvent),
                "call.missed" => typeof(CallMissedEvent),
                "call.moderation_blur" => typeof(CallModerationBlurEvent),
                "call.moderation_warning" => typeof(CallModerationWarningEvent),
                "call.notification" => typeof(CallNotificationEvent),
                "call.permission_request" => typeof(PermissionRequestEvent),
                "call.permissions_updated" => typeof(UpdatedCallPermissionsEvent),
                "call.reaction_new" => typeof(CallReactionEvent),
                "call.recording_failed" => typeof(CallRecordingFailedEvent),
                "call.recording_ready" => typeof(CallRecordingReadyEvent),
                "call.recording_started" => typeof(CallRecordingStartedEvent),
                "call.recording_stopped" => typeof(CallRecordingStoppedEvent),
                "call.rejected" => typeof(CallRejectedEvent),
                "call.ring" => typeof(CallRingEvent),
                "call.rtmp_broadcast_failed" => typeof(CallRtmpBroadcastFailedEvent),
                "call.rtmp_broadcast_started" => typeof(CallRtmpBroadcastStartedEvent),
                "call.rtmp_broadcast_stopped" => typeof(CallRtmpBroadcastStoppedEvent),
                "call.session_ended" => typeof(CallSessionEndedEvent),
                "call.session_participant_count_updated" => typeof(CallSessionParticipantCountsUpdatedEvent),
                "call.session_participant_joined" => typeof(CallSessionParticipantJoinedEvent),
                "call.session_participant_left" => typeof(CallSessionParticipantLeftEvent),
                "call.session_started" => typeof(CallSessionStartedEvent),
                "call.stats_report_ready" => typeof(CallStatsReportReadyEvent),
                "call.transcription_failed" => typeof(CallTranscriptionFailedEvent),
                "call.transcription_ready" => typeof(CallTranscriptionReadyEvent),
                "call.transcription_started" => typeof(CallTranscriptionStartedEvent),
                "call.transcription_stopped" => typeof(CallTranscriptionStoppedEvent),
                "call.unblocked_user" => typeof(UnblockedUserEvent),
                "call.updated" => typeof(CallUpdatedEvent),
                "call.user_feedback_submitted" => typeof(CallUserFeedbackSubmittedEvent),
                "call.user_muted" => typeof(CallUserMutedEvent),
                "campaign.completed" => typeof(CampaignCompletedEvent),
                "campaign.started" => typeof(CampaignStartedEvent),
                "channel.created" => typeof(ChannelCreatedEvent),
                "channel.deleted" => typeof(ChannelDeletedEvent),
                "channel.frozen" => typeof(ChannelFrozenEvent),
                "channel.hidden" => typeof(ChannelHiddenEvent),
                "channel.max_streak_changed" => typeof(MaxStreakChangedEvent),
                "channel.muted" => typeof(ChannelMutedEvent),
                "channel.truncated" => typeof(ChannelTruncatedEvent),
                "channel.unfrozen" => typeof(ChannelUnFrozenEvent),
                "channel.unmuted" => typeof(ChannelUnmutedEvent),
                "channel.updated" => typeof(ChannelUpdatedEvent),
                "channel.visible" => typeof(ChannelVisibleEvent),
                "channel_batch_update.completed" => typeof(ChannelBatchCompletedEvent),
                "channel_batch_update.started" => typeof(ChannelBatchStartedEvent),
                "custom" => typeof(CustomVideoEvent),
                "export.bulk_image_moderation.error" => typeof(AsyncExportErrorEvent),
                "export.bulk_image_moderation.success" => typeof(AsyncBulkImageModerationEvent),
                "export.channels.error" => typeof(AsyncExportErrorEvent),
                "export.channels.success" => typeof(AsyncExportChannelsEvent),
                "export.moderation_logs.error" => typeof(AsyncExportErrorEvent),
                "export.moderation_logs.success" => typeof(AsyncExportModerationLogsEvent),
                "export.users.error" => typeof(AsyncExportErrorEvent),
                "export.users.success" => typeof(AsyncExportUsersEvent),
                "feeds.activity.added" => typeof(ActivityAddedEvent),
                "feeds.activity.deleted" => typeof(ActivityDeletedEvent),
                "feeds.activity.feedback" => typeof(ActivityFeedbackEvent),
                "feeds.activity.marked" => typeof(ActivityMarkEvent),
                "feeds.activity.pinned" => typeof(ActivityPinnedEvent),
                "feeds.activity.reaction.added" => typeof(ActivityReactionAddedEvent),
                "feeds.activity.reaction.deleted" => typeof(ActivityReactionDeletedEvent),
                "feeds.activity.reaction.updated" => typeof(ActivityReactionUpdatedEvent),
                "feeds.activity.removed_from_feed" => typeof(ActivityRemovedFromFeedEvent),
                "feeds.activity.restored" => typeof(ActivityRestoredEvent),
                "feeds.activity.unpinned" => typeof(ActivityUnpinnedEvent),
                "feeds.activity.updated" => typeof(ActivityUpdatedEvent),
                "feeds.bookmark.added" => typeof(BookmarkAddedEvent),
                "feeds.bookmark.deleted" => typeof(BookmarkDeletedEvent),
                "feeds.bookmark.updated" => typeof(BookmarkUpdatedEvent),
                "feeds.bookmark_folder.deleted" => typeof(BookmarkFolderDeletedEvent),
                "feeds.bookmark_folder.updated" => typeof(BookmarkFolderUpdatedEvent),
                "feeds.comment.added" => typeof(CommentAddedEvent),
                "feeds.comment.deleted" => typeof(CommentDeletedEvent),
                "feeds.comment.reaction.added" => typeof(CommentReactionAddedEvent),
                "feeds.comment.reaction.deleted" => typeof(CommentReactionDeletedEvent),
                "feeds.comment.reaction.updated" => typeof(CommentReactionUpdatedEvent),
                "feeds.comment.restored" => typeof(CommentRestoredEvent),
                "feeds.comment.updated" => typeof(CommentUpdatedEvent),
                "feeds.feed.created" => typeof(FeedCreatedEvent),
                "feeds.feed.deleted" => typeof(FeedDeletedEvent),
                "feeds.feed.updated" => typeof(FeedUpdatedEvent),
                "feeds.feed_group.changed" => typeof(FeedGroupChangedEvent),
                "feeds.feed_group.deleted" => typeof(FeedGroupDeletedEvent),
                "feeds.feed_group.restored" => typeof(FeedGroupRestoredEvent),
                "feeds.feed_member.added" => typeof(FeedMemberAddedEvent),
                "feeds.feed_member.removed" => typeof(FeedMemberRemovedEvent),
                "feeds.feed_member.updated" => typeof(FeedMemberUpdatedEvent),
                "feeds.follow.created" => typeof(FollowCreatedEvent),
                "feeds.follow.deleted" => typeof(FollowDeletedEvent),
                "feeds.follow.updated" => typeof(FollowUpdatedEvent),
                "feeds.notification_feed.updated" => typeof(NotificationFeedUpdatedEvent),
                "feeds.stories_feed.updated" => typeof(StoriesFeedUpdatedEvent),
                "flag.updated" => typeof(FlagUpdatedEvent),
                "ingress.error" => typeof(IngressErrorEvent),
                "ingress.started" => typeof(IngressStartedEvent),
                "ingress.stopped" => typeof(IngressStoppedEvent),
                "member.added" => typeof(MemberAddedEvent),
                "member.removed" => typeof(MemberRemovedEvent),
                "member.updated" => typeof(MemberUpdatedEvent),
                "message.deleted" => typeof(MessageDeletedEvent),
                "message.flagged" => typeof(MessageFlaggedEvent),
                "message.new" => typeof(MessageNewEvent),
                "message.pending" => typeof(PendingMessageEvent),
                "message.read" => typeof(MessageReadEvent),
                "message.unblocked" => typeof(MessageUnblockedEvent),
                "message.undeleted" => typeof(MessageUndeletedEvent),
                "message.updated" => typeof(MessageUpdatedEvent),
                "moderation.custom_action" => typeof(ModerationCustomActionEvent),
                "moderation.flagged" => typeof(ModerationFlaggedEvent),
                "moderation.mark_reviewed" => typeof(ModerationMarkReviewedEvent),
                "moderation_check.completed" => typeof(ModerationCheckCompletedEvent),
                "moderation_rule.triggered" => typeof(ModerationRulesTriggeredEvent),
                "notification.mark_unread" => typeof(NotificationMarkUnreadEvent),
                "notification.reminder_due" => typeof(ReminderNotificationEvent),
                "notification.thread_message_new" => typeof(NotificationThreadMessageNewEvent),
                "reaction.deleted" => typeof(ReactionDeletedEvent),
                "reaction.new" => typeof(ReactionNewEvent),
                "reaction.updated" => typeof(ReactionUpdatedEvent),
                "reminder.created" => typeof(ReminderCreatedEvent),
                "reminder.deleted" => typeof(ReminderDeletedEvent),
                "reminder.updated" => typeof(ReminderUpdatedEvent),
                "review_queue_item.new" => typeof(ReviewQueueItemNewEvent),
                "review_queue_item.updated" => typeof(ReviewQueueItemUpdatedEvent),
                "thread.updated" => typeof(ThreadUpdatedEvent),
                "user.banned" => typeof(UserBannedEvent),
                "user.deactivated" => typeof(UserDeactivatedEvent),
                "user.deleted" => typeof(UserDeletedEvent),
                "user.flagged" => typeof(UserFlaggedEvent),
                "user.messages.deleted" => typeof(UserMessagesDeletedEvent),
                "user.muted" => typeof(UserMutedEvent),
                "user.reactivated" => typeof(UserReactivatedEvent),
                "user.unbanned" => typeof(UserUnbannedEvent),
                "user.unmuted" => typeof(UserUnmutedEvent),
                "user.unread_message_reminder" => typeof(UserUnreadReminderEvent),
                "user.updated" => typeof(UserUpdatedEvent),
                "user_group.created" => typeof(UserGroupCreatedEvent),
                "user_group.deleted" => typeof(UserGroupDeletedEvent),
                "user_group.member_added" => typeof(UserGroupMemberAddedEvent),
                "user_group.member_removed" => typeof(UserGroupMemberRemovedEvent),
                "user_group.updated" => typeof(UserGroupUpdatedEvent),
                _ => null
            };
        }

        /// <summary>
        /// Exception thrown when webhook operations fail.
        /// </summary>
        public class WebhookException : Exception
        {
            public WebhookException(string message) : base(message)
            {
            }

            public WebhookException(string message, Exception innerException) : base(message, innerException)
            {
            }
        }

        /// <summary>
        /// Verify the HMAC-SHA256 signature of a webhook payload.
        /// </summary>
        /// <param name="body">The raw request body as a byte array</param>
        /// <param name="signature">The signature from the X-Signature header</param>
        /// <param name="secret">Your webhook secret (found in the Stream Dashboard)</param>
        /// <returns>true if the signature is valid, false otherwise</returns>
        public static bool VerifySignature(byte[] body, string signature, string secret)
        {
            using var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(secret));
            var hash = hmac.ComputeHash(body);
            var expected = Convert.ToHexString(hash).ToLowerInvariant();

#if NET5_0_OR_GREATER
            return CryptographicOperations.FixedTimeEquals(
                Encoding.UTF8.GetBytes(signature),
                Encoding.UTF8.GetBytes(expected)
            );
#else
            // Fallback for older .NET versions - constant time comparison
            if (signature.Length != expected.Length)
                return false;

            uint result = 0;
            for (int i = 0; i < signature.Length; i++)
            {
                result |= (uint)(signature[i] ^ expected[i]);
            }
            return result == 0;
#endif
        }

        /// <summary>
        /// Verify the HMAC-SHA256 signature of a webhook payload.
        /// </summary>
        /// <param name="body">The raw request body as a string</param>
        /// <param name="signature">The signature from the X-Signature header</param>
        /// <param name="secret">Your webhook secret (found in the Stream Dashboard)</param>
        /// <returns>true if the signature is valid, false otherwise</returns>
        public static bool VerifySignature(string body, string signature, string secret)
        {
            return VerifySignature(Encoding.UTF8.GetBytes(body), signature, secret);
        }
    }
}
